CREATE DATABASE HEALTHREPORTS_DB;
USE HEALTHREPORTS_DB;

-- PATIENTS TABLE 
CREATE TABLE PATIENTS
(
  PATIENT_ID INT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  AGE INT NOT NULL,
  GENDER ENUM("M","F","OTHER") NOT NULL,
  CONTACT BIGINT UNIQUE,
  MEDICAL_HISTORY TEXT
);

-- DOCTORS TABLE 
CREATE TABLE DOCTORS 
(
  DOCTOR_ID INT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SPECIALIZATION VARCHAR(100) NOT NULL,
  CONTACT BIGINT UNIQUE,
  AVAILABLE_DAYS TEXT
);

-- APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS
(
  APPOINTMENT_ID INT PRIMARY KEY,
  PATIENT_ID INT,
  DOCTOR_ID INT,
  DATE DATETIME,
  STATUS ENUM("SCHEDULED","COMPLETED","CANCELLED") DEFAULT "SCHEDULED",
  CONSTRAINT PATIENTS_APP_FK FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
  CONSTRAINT DOCTORS_APP_FK FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
);

-- RECORDS TABLE 
CREATE TABLE RECORDS 
(
  RECORD_ID INT PRIMARY KEY,
  PATIENT_ID INT,
  DOCTOR_ID INT,
  DIAGNOSIS TEXT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PATIENTS_RECORD_FK FOREIGN KEY(PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
  CONSTRAINT DOCTORS_RECORDS_FK FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
);

-- USERS TABLE 
CREATE TABLE USERS
(
  USER_ID INT PRIMARY KEY,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE ENUM("DOCTOR","PATIENT","ADMIN")
);

SHOW TABLES;
